### ISSUE TITLE
Reading morgue seems broken for this character

### ISSUE THREAD

**Issue by jfcaron3** [ezmonkey4/dcssfamiliar-angular#7]
I don't know if it's Ashenzari or 0.25 spells or what.  It doesn't get my stats, spells, or equipment right.

[morgue.txt](https://github.com/ezmonkey4/dcssfamiliar-angular/files/5066728/morgue.txt)

**Comment by ezmonkey4** [comment]
Hi jfcaron3,

The tool seems to break with "Frozen Ramparts" and "Absolute Zero" spells.
I'll have a look to see why these two spells are causing some issues.

Regards,
Luís

**Comment by lmorao** [comment]
I messed up linking the fix, but it is fixed. by the commit above
